### ISSUE TITLE
关于SWRM在MOSI-Gold上的表现问题

### ISSUE THREAD

**Issue by LingFengGold** [albertwy/SWRM#5]
您好！
我看到论文中report了SWRM在MOSI-SpeechBrain, MOSI-IBM, and MOSI-iFlytek数据集上的效果，请问作者有没有试过在MOSI-Gold上运行SWRM，表现如何呢？

**Comment by albertwy** [comment]
你好！
SWRM针对的是带有ASR噪音的多模态情感分析，因为我们使用的融合方法与Self-MM相同，所以Self-MM在MOSI-Gold上的结果可以看成SWRM的性能上界。
但是，我们没有尝试过直接在MOSI-Gold上进行衡量性能，因为我们引入的Refinement模块的一个隐式前提是文本带有ASR噪音。
如果在MOSI-Gold进行实验，实验的设置就发生了变化，对于无噪音下的多模态情感分析，有别的很多工作（如MulT，Self-MM等）也可以参考。

**Comment by LingFengGold** [comment]
好的了解了，非常感谢！
